version: '3'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/2πR:/var/www
    networks:
      - app-network
    depends_on:
      - postgres-db
    ports:
      - 8000:8000
    command: >
      bash -c "composer install && bin/console doctrine:migrations:migrate --no-interaction && php -S 0.0.0.0:8000 -t public"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/2πR:/usr/share/nginx/html:ro
    ports:
      - 8080:80
    networks:
      - app-network
    depends_on:
      - php-fpm


  postgres-db:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: deuxpir
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - app-network
    depends_on:
      - postgres-db

volumes:
  postgresql_data:

networks:
  app-network: